### Bag of words: Exercises


- In this Exercise, you are going to classify whether a given movie review is **positive or negative**.
- you are going to use Bag of words for pre-processing the text and apply different classification algorithms.
- Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

In [1]:
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

### **About Data: IMDB Dataset**

Credits: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download


- This data consists of two columns.
        - review
        - sentiment
- Reviews are the statements given by users after watching the movie.
- sentiment feature tells whether the given review is positive or negative.

In [4]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
df = pd.read_csv('movies_sentiment_data.csv')


#2. print the shape of the data
print(df.shape)


#3. print top 5 datapoints
df.head()

(19000, 2)

                                              review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [5]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative
df['Category'] = df['sentiment'].apply(lambda x: 1 if x == 'positive' else 0)
df

                                                  review sentiment  Category
0      I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1      I enjoyed the movie and the story immensely! I...  positive         1
2      I had a hard time sitting through this. Every ...  negative         0
3      It's hard to imagine that anyone could find th...  negative         0
4      This is one military drama I like a lot! Tom B...  positive         1
...                                                  ...       ...       ...
18995  - Bad Stuff: This movie is real crap. Bad stun...  negative         0
18996  If you've seen the trailer for this movie, you...  positive         1
18997  This has to be the all time best computer anim...  positive         1
18998  I've seen 'NSNA' just after I've seen all Roge...  positive         1
18999  Norris plays a Chicago cop who stumbles upon a...  negative         0

[19000 rows x 3 columns]

In [6]:
df.drop('sentiment', axis=1, inplace=True)
df

                                                  review  Category
0      I first saw Jake Gyllenhaal in Jarhead (2005) ...         1
1      I enjoyed the movie and the story immensely! I...         1
2      I had a hard time sitting through this. Every ...         0
3      It's hard to imagine that anyone could find th...         0
4      This is one military drama I like a lot! Tom B...         1
...                                                  ...       ...
18995  - Bad Stuff: This movie is real crap. Bad stun...         0
18996  If you've seen the trailer for this movie, you...         1
18997  This has to be the all time best computer anim...         1
18998  I've seen 'NSNA' just after I've seen all Roge...         1
18999  Norris plays a Chicago cop who stumbles upon a...         0

[19000 rows x 2 columns]

In [7]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.
print(df['Category'].value_counts())

Category
1    9500
0    9500
Name: count, dtype: int64

In [8]:
#Do the 'train-test' splitting with test size of 20%
X_train, X_test, y_train, y_test = train_test_split(df['review'], df['Category'], test_size=0.2, random_state=42)

**Exercise-1**

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.

**Note:**
- use CountVectorizer for pre-processing the text.

- use **Random Forest** as the classifier with estimators as 50 and criterion as entropy.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [9]:
#1. create a pipeline object
clf=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', RandomForestClassifier(n_estimators=50,criterion='entropy'))
])



#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.85      0.83      1864
           1       0.85      0.82      0.84      1936

    accuracy                           0.84      3800
   macro avg       0.84      0.84      0.84      3800
weighted avg       0.84      0.84      0.84      3800

**Exercise-2**

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

**Note:**
- use CountVectorizer for pre-processing the text.
- use **KNN** as the classifier with n_neighbors of 10 and metric as 'euclidean'.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [10]:
#1. create a pipeline object
clf=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', KNeighborsClassifier(n_neighbors=10, metric='euclidean'))
])



#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.64      0.64      0.64      1864
           1       0.65      0.65      0.65      1936

    accuracy                           0.65      3800
   macro avg       0.65      0.65      0.65      3800
weighted avg       0.65      0.65      0.65      3800

**Exercise-3**

1. using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

**Note:**
- use CountVectorizer for pre-processing the text.
- use **Multinomial Naive Bayes** as the classifier.
- print the classification report.

**References**:

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

In [11]:
#1. create a pipeline object
clf=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', MultinomialNB())
])



#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1864
           1       0.87      0.81      0.84      1936

    accuracy                           0.84      3800
   macro avg       0.85      0.84      0.84      3800
weighted avg       0.85      0.84      0.84      3800

### Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?

## [**Solution**](./bag_of_words_exercise_solutions.ipynb)