In [1]:
import pandas as pd
df=pd.read_csv('heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [2]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [3]:
zscore1=(df.RestingBP-df.RestingBP.mean())/df.RestingBP.std()
zscore2=(df.Cholesterol-df.Cholesterol.mean())/df.Cholesterol.std()
zscore3=(df.MaxHR-df.MaxHR.mean())/df.MaxHR.std()
zscore4=(df.Oldpeak-df.Oldpeak.mean())/df.Oldpeak.std()

In [4]:
df[['zscore1','zscore2','zscore3','zscore4']] = pd.concat([zscore1, zscore2, zscore3, zscore4], axis=1).values
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068,-0.188897,0.293123
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020,0.164595,2.355810
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090,1.460728,-0.831979
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578,1.421452,-0.831979

In [5]:
df1 = df[
    (df.zscore1 > -3) & (df.zscore1 < 3) &
    (df.zscore2 > -3) & (df.zscore2 < 3) &
    (df.zscore3 > -3) & (df.zscore3 < 3) &
    (df.zscore4 > -3) & (df.zscore4 < 3)
]
df1

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068,-0.188897,0.293123
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020,0.164595,2.355810
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090,1.460728,-0.831979
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578,1.421452,-0.831979

In [6]:
x=df.drop((['HeartDisease','zscore1','zscore2','zscore3','zscore4']),axis=1)
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [7]:
y=df.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [10]:
dfle=df1
dfle.Sex=le.fit_transform(dfle.Sex)
dfle.ChestPainType=le.fit_transform(dfle.ChestPainType)
dfle.RestingECG=le.fit_transform(dfle.RestingECG)
dfle.ExerciseAngina=le.fit_transform(dfle.ExerciseAngina)
dfle.ST_Slope=le.fit_transform(dfle.ST_Slope)
dfle

/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_53333/450425827.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.Sex=le.fit_transform(dfle.Sex)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_53333/450425827.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.ChestPainType=le.fit_transform(dfle.ChestPainType)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_53333/450425827.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.RestingECG=le.fit_transform(dfle.RestingECG)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_53333/450425827.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.ExerciseAngina=le.fit_transform(dfle.ExerciseAngina)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_53333/450425827.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.ST_Slope=le.fit_transform(dfle.ST_Slope)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,1,1,140,289,0,1,172,0,0.0,2,0,0.410685,0.824621,1.382175,-0.831979
1,49,0,2,160,180,0,1,156,0,1.0,1,1,1.490940,-0.171867,0.753746,0.105606
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.302660,0.138964,-1.131539,0.574398
4,54,1,2,150,195,0,1,122,0,0.0,2,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,-1.209697,0.596068,-0.188897,0.293123
914,68,1,0,144,193,1,1,141,0,3.4,1,1,0.626736,-0.053020,0.164595,2.355810
915,57,1,0,130,131,0,1,115,1,1.2,1,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.129442,0.340090,1.460728,-0.831979
917,38,1,2,138,175,0,1,173,0,0.0,2,0,0.302660,-0.217578,1.421452,-0.831979

In [11]:
x=df1.drop((['HeartDisease','zscore1','zscore2','zscore3','zscore4']),axis=1)
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1
914,68,1,0,144,193,1,1,141,0,3.4,1
915,57,1,0,130,131,0,1,115,1,1.2,1
916,57,0,1,130,236,0,0,174,0,0.0,1
917,38,1,2,138,175,0,1,173,0,0.0,2

In [12]:
y=df1.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 899, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)
X_scaled

array([[-1.42815446,  0.515943  ,  0.2245723 , ..., -0.8229452 ,
        -0.85546862,  1.04249607],
       [-0.47585532, -1.93819859,  1.27063705, ..., -0.8229452 ,
         0.13751561, -0.62216462],
       [-1.7455875 ,  0.515943  ,  0.2245723 , ..., -0.8229452 ,
        -0.85546862,  1.04249607],
       ...,
       [ 0.3706328 ,  0.515943  , -0.82149245, ...,  1.21514774,
         0.33611246, -0.62216462],
       [ 0.3706328 , -1.93819859,  0.2245723 , ..., -0.8229452 ,
        -0.85546862, -0.62216462],
       [-1.63977649,  0.515943  ,  1.27063705, ..., -0.8229452 ,
        -0.85546862,  1.04249607]])

In [118]:
df1

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,1,1,140,289,0,1,172,0,0.0,2,0,0.410685,0.824621,1.382175,-0.831979
1,49,0,2,160,180,0,1,156,0,1.0,1,1,1.490940,-0.171867,0.753746,0.105606
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.302660,0.138964,-1.131539,0.574398
4,54,1,2,150,195,0,1,122,0,0.0,2,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,-1.209697,0.596068,-0.188897,0.293123
914,68,1,0,144,193,1,1,141,0,3.4,1,1,0.626736,-0.053020,0.164595,2.355810
915,57,1,0,130,131,0,1,115,1,1.2,1,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.129442,0.340090,1.460728,-0.831979
917,38,1,2,138,175,0,1,173,0,0.0,2,0,0.302660,-0.217578,1.421452,-0.831979

In [14]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
            'C': [1, 5, 10]
        }
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'max_depth': [None, 5, 10],
            'criterion': ['gini', 'entropy']
        }
    }
}

In [15]:
score=[]
cv_results_list = []
for models,mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(X_scaled,y)
    score.append({
        'model':models,
        'best_params':clf.best_params_,
        'best_score':clf.best_score_
    })
     #Add detailed cv_results_
    results_df = pd.DataFrame(clf.cv_results_)
    results_df['model'] = models  # Add model name column
    cv_results_list.append(results_df)


df=pd.DataFrame(score,columns=['model','best_score','best_params'])
df

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

                 model  best_score                               best_params
0                  svm    0.826400                 {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.815264                      {'n_estimators': 10}
2  logistic_regression    0.801924                                  {'C': 1}
3        decision_tree    0.788566  {'criterion': 'entropy', 'max_depth': 5}

In [16]:
cv_details = pd.concat(cv_results_list, ignore_index=True)
cv_details

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score,model,param_n_estimators,param_criterion,param_max_depth
0,0.007014,0.002965,0.002431,3.294425e-04,1.0,rbf,"{'C': 1, 'kernel': 'rbf'}",0.844444,0.861111,0.838889,0.827778,0.759777,0.826400,0.035006,1,svm,NaN,NaN,NaN
1,0.005444,0.000783,0.000860,1.294759e-04,1.0,linear,"{'C': 1, 'kernel': 'linear'}",0.822222,0.800000,0.850000,0.844444,0.743017,0.811937,0.038740,4,svm,NaN,NaN,NaN
2,0.004523,0.000459,0.001379,1.275993e-04,10.0,rbf,"{'C': 10, 'kernel': 'rbf'}",0.800000,0.816667,0.850000,0.822222,0.759777,0.809733,0.029718,5,svm,NaN,NaN,NaN
3,0.017152,0.002471,0.000530,2.366352e-05,10.0,linear,"{'C': 10, 'kernel': 'linear'}",0.827778,0.800000,0.850000,0.844444,0.748603,0.814165,0.037109,3,svm,NaN,NaN,NaN
4,0.004659,0.000384,0.001255,8.550862e-05,20.0,rbf,"{'C': 20, 'kernel': 'rbf'}",0.788889,0.833333,0.833333,0.805556,0.743017,0.800826,0.033527,6,svm,NaN,NaN,NaN
5,0.029629,0.005453,0.000528,2.360561e-05,20.0,linear,"{'C': 20, 'kernel': 'linear'}",0.827778,0.800000,0.850000,0.844444,0.754190,0.815282,0.035150,2,svm,NaN,NaN,NaN
6,0.000921,0.000078,0.000265,1.420543e-05,NaN,NaN,{'n_estimators': 1},0.811111,0.761111,0.744444,0.733333,0.642458,0.738492,0.054899,3,random_forest,1.0,NaN,NaN
7,0.003037,0.000069,0.000338,3.300182e-06,NaN,NaN,{'n_estimators': 5},0.844444,0.844444,0.805556,0.800000,0.720670,0.803023,0.045230,2,random_forest,5.0,NaN,NaN
8,0.005656,0.000072,0.000441,3.211490e-06,NaN,NaN,{'n_estimators': 10},0.861111,0.811111,0.816667,0.850000,0.737430,0.815264,0.043326,1,random_forest,10.0,NaN,NaN
9,0.000882,0.000776,0.000174,1.080917e-05,1.0,NaN,{'C': 1},0.805556,0.822222,0.827778,0.822222,0.731844,0.801924,0.035824,1,logistic_regression,NaN,NaN,NaN
10,0.000472,0.000025,0.000163,1.266988e-06,5.0,NaN,{'C': 5},0.805556,0.822222,0.827778,0.822222,0.731844,0.801924,0.035824,1,logistic_regression,NaN,NaN,NaN
11,0.000467,0.000022,0.000164,3.377138e-06,10.0,NaN,{'C': 10},0.805556,0.822222,0.827778,0.822222,0.731844,0.801924,0.035824,1,logistic_regression,NaN,NaN,NaN
12,0.001249,0.000085,0.000184,4.252682e-06,NaN,NaN,"{'criterion': 'gini', 'max_depth': None}",0.794444,0.788889,0.783333,0.733333,0.648045,0.749609,0.055264,6,decision_tree,NaN,gini,None
13,0.000855,0.000025,0.000177,1.417739e-06,NaN,NaN,"{'criterion': 'gini', 'max_depth': 5}",0.894444,0.816667,0.772222,0.738889,0.681564,0.780757,0.071943,2,decision_tree,NaN,gini,5
14,0.001194,0.000061,0.000177,8.714517e-07,NaN,NaN,"{'criterion': 'gini', 'max_depth': 10}",0.805556,0.788889,0.794444,0.738889,0.670391,0.759634,0.050142,4,decision_tree,NaN,gini,10
15,0.001291,0.000071,0.000178,3.777562e-06,NaN,NaN,"{'criterion': 'entropy', 'max_depth': None}",0.794444,0.755556,0.794444,0.733333,0.681564,0.751868,0.042250,5,decision_tree,NaN,entropy,None
16,0.000921,0.000027,0.000174,2.042066e-06,NaN,NaN,"{'criterion': 'entropy', 'max_depth': 5}",0.883333,0.788889,0.788889,0.772222,0.709497,0.788566,0.055678,1,decision_tree,NaN,entropy,5
17,0.001251,0.000059,0.000179,4.809678e-06,NaN,NaN,"{'criterion': 'entropy', 'max_depth': 10}",0.800000,0.783333,0.794444,0.755556,0.670391,0.760745,0.047702,3,decision_tree,NaN,entropy,10

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y, random_state=10)

In [48]:
from sklearn.model_selection import cross_val_score
score1 = cross_val_score(svm.SVC(), x, y, cv=5)
score1,score1.mean()

(array([0.62222222, 0.78888889, 0.68888889, 0.72222222, 0.62011173]),
 0.6884667908131595)

In [47]:
from sklearn.ensemble import BaggingClassifier
bagging1=BaggingClassifier(
    estimator=svm.SVC(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
cross_val_score(bagging1,x,y,cv=5),cross_val_score(bagging1,x,y,cv=5).mean()

(array([0.63888889, 0.78888889, 0.68888889, 0.70555556, 0.61452514]),
 0.6873494723774053)

In [52]:
score3 = cross_val_score(DecisionTreeClassifier(), x, y, cv=5)
score3,score3.mean()

(array([0.81111111, 0.76111111, 0.77222222, 0.76666667, 0.61452514]),
 0.7451272501551831)

In [50]:
bagging2=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
cross_val_score(bagging2,x,y,cv=5),cross_val_score(bagging2,x,y,cv=5).mean()

(array([0.88888889, 0.81111111, 0.82222222, 0.82222222, 0.72625698]),
 0.8141402855369335)

In [51]:
scores = cross_val_score(RandomForestClassifier(), x, y, cv=5)
scores.mean()

0.8230477963997517