In [106]:
import pandas as pd
df=pd.read_csv('heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [107]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [108]:
zscore1=(df.RestingBP-df.RestingBP.mean())/df.RestingBP.std()
zscore2=(df.Cholesterol-df.Cholesterol.mean())/df.Cholesterol.std()
zscore3=(df.MaxHR-df.MaxHR.mean())/df.MaxHR.std()
zscore4=(df.Oldpeak-df.Oldpeak.mean())/df.Oldpeak.std()

In [109]:
df[['zscore1','zscore2','zscore3','zscore4']] = pd.concat([zscore1, zscore2, zscore3, zscore4], axis=1).values
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068,-0.188897,0.293123
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020,0.164595,2.355810
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090,1.460728,-0.831979
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578,1.421452,-0.831979

In [110]:
df1 = df[
    (df.zscore1 > -3) & (df.zscore1 < 3) &
    (df.zscore2 > -3) & (df.zscore2 < 3) &
    (df.zscore3 > -3) & (df.zscore3 < 3) &
    (df.zscore4 > -3) & (df.zscore4 < 3)
]
df1

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068,-0.188897,0.293123
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020,0.164595,2.355810
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090,1.460728,-0.831979
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578,1.421452,-0.831979

In [111]:
x=df.drop('HeartDisease',axis=1)
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,zscore1,zscore2,zscore3,zscore4
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,-1.209697,0.596068,-0.188897,0.293123
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,0.626736,-0.053020,0.164595,2.355810
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,-0.129442,-0.619830,-0.856602,0.293123
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,-0.129442,0.340090,1.460728,-0.831979
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0.302660,-0.217578,1.421452,-0.831979

In [112]:
y=df.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [113]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [114]:
dfle=df1
dfle.Sex=le.fit_transform(dfle.Sex)
dfle.ChestPainType=le.fit_transform(dfle.ChestPainType)
dfle.RestingECG=le.fit_transform(dfle.RestingECG)
dfle.ExerciseAngina=le.fit_transform(dfle.ExerciseAngina)
dfle.ST_Slope=le.fit_transform(dfle.ST_Slope)
dfle

/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_31434/450425827.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.Sex=le.fit_transform(dfle.Sex)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_31434/450425827.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.ChestPainType=le.fit_transform(dfle.ChestPainType)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_31434/450425827.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.RestingECG=le.fit_transform(dfle.RestingECG)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_31434/450425827.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.ExerciseAngina=le.fit_transform(dfle.ExerciseAngina)
/var/folders/vj/jkftb76576g6gntjkl2_4b0w0000gn/T/ipykernel_31434/450425827.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.ST_Slope=le.fit_transform(dfle.ST_Slope)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,1,1,140,289,0,1,172,0,0.0,2,0,0.410685,0.824621,1.382175,-0.831979
1,49,0,2,160,180,0,1,156,0,1.0,1,1,1.490940,-0.171867,0.753746,0.105606
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.302660,0.138964,-1.131539,0.574398
4,54,1,2,150,195,0,1,122,0,0.0,2,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,-1.209697,0.596068,-0.188897,0.293123
914,68,1,0,144,193,1,1,141,0,3.4,1,1,0.626736,-0.053020,0.164595,2.355810
915,57,1,0,130,131,0,1,115,1,1.2,1,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.129442,0.340090,1.460728,-0.831979
917,38,1,2,138,175,0,1,173,0,0.0,2,0,0.302660,-0.217578,1.421452,-0.831979

In [115]:
x=df1.drop('HeartDisease',axis=1)
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,zscore1,zscore2,zscore3,zscore4
0,40,1,1,140,289,0,1,172,0,0.0,2,0.410685,0.824621,1.382175,-0.831979
1,49,0,2,160,180,0,1,156,0,1.0,1,1.490940,-0.171867,0.753746,0.105606
2,37,1,1,130,283,0,2,98,0,0.0,2,-0.129442,0.769768,-1.524307,-0.831979
3,48,0,0,138,214,0,1,108,1,1.5,1,0.302660,0.138964,-1.131539,0.574398
4,54,1,2,150,195,0,1,122,0,0.0,2,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,-1.209697,0.596068,-0.188897,0.293123
914,68,1,0,144,193,1,1,141,0,3.4,1,0.626736,-0.053020,0.164595,2.355810
915,57,1,0,130,131,0,1,115,1,1.2,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,0,1,130,236,0,0,174,0,0.0,1,-0.129442,0.340090,1.460728,-0.831979
917,38,1,2,138,175,0,1,173,0,0.0,2,0.302660,-0.217578,1.421452,-0.831979

In [116]:
y=df1.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 899, dtype: int64

In [117]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)
X_scaled

array([[-1.42815446,  0.515943  ,  0.2245723 , ...,  0.84963584,
         1.38431998, -0.85546862],
       [-0.47585532, -1.93819859,  1.27063705, ..., -0.16812204,
         0.7529728 ,  0.13751561],
       [-1.7455875 ,  0.515943  ,  0.2245723 , ...,  0.79361247,
        -1.53566071, -0.85546862],
       ...,
       [ 0.3706328 ,  0.515943  , -0.82149245, ..., -0.62564622,
        -0.86485434,  0.33611246],
       [ 0.3706328 , -1.93819859,  0.2245723 , ...,  0.35476274,
         1.46323838, -0.85546862],
       [-1.63977649,  0.515943  ,  1.27063705, ..., -0.21480818,
         1.42377918, -0.85546862]])

In [118]:
df1

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore1,zscore2,zscore3,zscore4
0,40,1,1,140,289,0,1,172,0,0.0,2,0,0.410685,0.824621,1.382175,-0.831979
1,49,0,2,160,180,0,1,156,0,1.0,1,1,1.490940,-0.171867,0.753746,0.105606
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.302660,0.138964,-1.131539,0.574398
4,54,1,2,150,195,0,1,122,0,0.0,2,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,-1.209697,0.596068,-0.188897,0.293123
914,68,1,0,144,193,1,1,141,0,3.4,1,1,0.626736,-0.053020,0.164595,2.355810
915,57,1,0,130,131,0,1,115,1,1.2,1,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.129442,0.340090,1.460728,-0.831979
917,38,1,2,138,175,0,1,173,0,0.0,2,0,0.302660,-0.217578,1.421452,-0.831979

In [119]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
            'C': [1, 5, 10]
        }
    }
}

In [120]:
score=[]
cv_results_list = []
for models,mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(X_scaled,y)
    score.append({
        'model':models,
        'best_params':clf.best_params_,
        'best_score':clf.best_score_
    })
     #Add detailed cv_results_
    results_df = pd.DataFrame(clf.cv_results_)
    results_df['model'] = models  # Add model name column
    cv_results_list.append(results_df)


df=pd.DataFrame(score,columns=['model','best_score','best_params'])
df

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

                 model  best_score                best_params
0                  svm    0.827511  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.813054        {'n_estimators': 5}
2  logistic_regression    0.801924                   {'C': 1}

In [121]:
cv_details = pd.concat(cv_results_list, ignore_index=True)
cv_details

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score,model,param_n_estimators
0,0.007242,0.003439,0.003637,0.001553,1.0,rbf,"{'C': 1, 'kernel': 'rbf'}",0.833333,0.883333,0.833333,0.827778,0.759777,0.827511,0.039426,1,svm,NaN
1,0.006295,0.001058,0.000722,0.000154,1.0,linear,"{'C': 1, 'kernel': 'linear'}",0.827778,0.800000,0.850000,0.844444,0.743017,0.813048,0.039097,4,svm,NaN
2,0.004632,0.000342,0.005494,0.001981,10.0,rbf,"{'C': 10, 'kernel': 'rbf'}",0.777778,0.838889,0.816667,0.816667,0.765363,0.803073,0.027255,5,svm,NaN
3,0.023308,0.003228,0.000572,0.000030,10.0,linear,"{'C': 10, 'kernel': 'linear'}",0.827778,0.800000,0.850000,0.844444,0.748603,0.814165,0.037109,3,svm,NaN
4,0.005190,0.000497,0.001362,0.000084,20.0,rbf,"{'C': 20, 'kernel': 'rbf'}",0.783333,0.833333,0.833333,0.805556,0.754190,0.801949,0.030366,6,svm,NaN
5,0.038263,0.003486,0.000615,0.000058,20.0,linear,"{'C': 20, 'kernel': 'linear'}",0.827778,0.800000,0.850000,0.844444,0.754190,0.815282,0.035150,2,svm,NaN
6,0.000922,0.000054,0.000269,0.000014,NaN,NaN,{'n_estimators': 1},0.850000,0.666667,0.661111,0.733333,0.620112,0.706245,0.080525,3,random_forest,1.0
7,0.003230,0.000123,0.000355,0.000007,NaN,NaN,{'n_estimators': 5},0.861111,0.816667,0.827778,0.811111,0.748603,0.813054,0.036598,1,random_forest,5.0
8,0.006090,0.000314,0.000460,0.000017,NaN,NaN,{'n_estimators': 10},0.800000,0.816667,0.833333,0.811111,0.720670,0.796356,0.039342,2,random_forest,10.0
9,0.000605,0.000092,0.000175,0.000011,1.0,NaN,{'C': 1},0.805556,0.822222,0.827778,0.822222,0.731844,0.801924,0.035824,1,logistic_regression,NaN
10,0.000553,0.000028,0.000328,0.000316,5.0,NaN,{'C': 5},0.805556,0.822222,0.827778,0.822222,0.731844,0.801924,0.035824,1,logistic_regression,NaN
11,0.000647,0.000104,0.000217,0.000053,10.0,NaN,{'C': 10},0.805556,0.822222,0.827778,0.822222,0.731844,0.801924,0.035824,1,logistic_regression,NaN

In [122]:
model=svm.SVC(C=1,kernel='rbf')
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X_scaled,y,test_size=0.2)

In [123]:
model.fit(xtrain,ytrain)

SVC(C=1)

model.score(xtest,ytest)

In [124]:
model.score(xtest,ytest)

0.8666666666666667

In [125]:
from sklearn.decomposition import PCA
pca=PCA(0.95)
pca_x=pca.fit_transform(X_scaled)
pca_x.shape

(899, 10)

In [126]:
df.shape

(3, 3)

In [127]:
pca.explained_variance_ratio_

array([0.25988011, 0.16619705, 0.12279718, 0.09615401, 0.06837992,
       0.0616307 , 0.05704865, 0.05493853, 0.04201985, 0.03785838])

In [128]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(pca_x, y, test_size=0.2, random_state=30)

model=svm.SVC(C=1,kernel='rbf')
model.fit(X_train_pca, y_train)
model.score(X_test_pca, y_test)

0.8666666666666667

In [130]:
df

                 model  best_score                best_params
0                  svm    0.827511  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.813054        {'n_estimators': 5}
2  logistic_regression    0.801924                   {'C': 1}